
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.fossilminecraft.init;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.eventbus.api.SubscribeEvent;
import net.minecraftforge.event.BuildCreativeModeTabContentsEvent;

import net.minecraft.world.item.ItemStack;
import net.minecraft.world.item.CreativeModeTabs;
import net.minecraft.world.item.CreativeModeTab;
import net.minecraft.network.chat.Component;
import net.minecraft.core.registries.Registries;

import net.mcreator.fossilminecraft.FossilMinecraftMod;

@Mod.EventBusSubscriber(bus = Mod.EventBusSubscriber.Bus.MOD)
public class FossilMinecraftModTabs {
	public static final DeferredRegister<CreativeModeTab> REGISTRY = DeferredRegister.create(Registries.CREATIVE_MODE_TAB, FossilMinecraftMod.MODID);
	public static final RegistryObject<CreativeModeTab> FOSSIL_MINECRAFT = REGISTRY.register("fossil_minecraft",
			() -> CreativeModeTab.builder().title(Component.translatable("item_group.fossil_minecraft.fossil_minecraft")).icon(() -> new ItemStack(FossilMinecraftModItems.TREX_SPAWN_EGG.get())).displayItems((parameters, tabData) -> {
				tabData.accept(FossilMinecraftModItems.TREX_SPAWN_EGG.get());
				tabData.accept(FossilMinecraftModItems.SHAN_SHAN_SPAWN_EGG.get());
				tabData.accept(FossilMinecraftModItems.VRAPTOR_SPAWN_EGG.get());
				tabData.accept(FossilMinecraftModItems.TREX_MEDAL.get());
				tabData.accept(FossilMinecraftModItems.SHANSHAN_MEDAL.get());
				tabData.accept(FossilMinecraftModItems.VRAPTOR_MEDAL.get());
				tabData.accept(FossilMinecraftModItems.SEIDON_SPAWN_EGG.get());
				tabData.accept(FossilMinecraftModItems.SEIDON_MEDAL.get());
				tabData.accept(FossilMinecraftModBlocks.CLEANER.get().asItem());
				tabData.accept(FossilMinecraftModBlocks.REVIVER.get().asItem());
				tabData.accept(FossilMinecraftModBlocks.FOSSIL.get().asItem());
				tabData.accept(FossilMinecraftModItems.TREX_HEAD.get());
				tabData.accept(FossilMinecraftModItems.SHANSHAN_HEAD.get());
				tabData.accept(FossilMinecraftModItems.EMPTY_MEDAL.get());
				tabData.accept(FossilMinecraftModItems.DRILL.get());
				tabData.accept(FossilMinecraftModItems.HAMMER.get());
				tabData.accept(FossilMinecraftModItems.SUPER_HAMMER.get());
				tabData.accept(FossilMinecraftModItems.SONAR.get());
				tabData.accept(FossilMinecraftModItems.SEIDON_HEAD.get());
				tabData.accept(FossilMinecraftModItems.URAPTOR_MEDAL.get());
				tabData.accept(FossilMinecraftModItems.CARCHAR_SPAWN_EGG.get());
			}).withSearchBar().build());
	public static final RegistryObject<CreativeModeTab> FOSSIL_MINECRAFT_FOSSILS = REGISTRY.register("fossil_minecraft_fossils",
			() -> CreativeModeTab.builder().title(Component.translatable("item_group.fossil_minecraft.fossil_minecraft_fossils")).icon(() -> new ItemStack(FossilMinecraftModItems.TREX_HEAD.get())).displayItems((parameters, tabData) -> {
				tabData.accept(FossilMinecraftModItems.UNKNOWN_FOSSIL.get());
				tabData.accept(FossilMinecraftModItems.SHANSHAN_FOSSIL.get());
				tabData.accept(FossilMinecraftModItems.SEIDON_HEAD_FOSSIL.get());
				tabData.accept(FossilMinecraftModItems.TREX_BODY.get());
				tabData.accept(FossilMinecraftModItems.TREX_ARMS.get());
				tabData.accept(FossilMinecraftModItems.TREX_LEGS.get());
				tabData.accept(FossilMinecraftModItems.DASPLETO_HEAD.get());
				tabData.accept(FossilMinecraftModItems.DASPLETO_BODY.get());
				tabData.accept(FossilMinecraftModItems.DASPLETO_ARMS.get());
				tabData.accept(FossilMinecraftModItems.DASPLETO_LEGS.get());
				tabData.accept(FossilMinecraftModItems.GORGO_HEAD.get());
				tabData.accept(FossilMinecraftModItems.GORGO_BODY.get());
				tabData.accept(FossilMinecraftModItems.GORGO_ARMS.get());
				tabData.accept(FossilMinecraftModItems.GORGO_LEGS.get());
				tabData.accept(FossilMinecraftModItems.TARBO_HEAD.get());
				tabData.accept(FossilMinecraftModItems.TARBO_BODY.get());
				tabData.accept(FossilMinecraftModItems.TARBO_ARMS.get());
				tabData.accept(FossilMinecraftModItems.TARBO_LEGS.get());
				tabData.accept(FossilMinecraftModItems.ALIO_HEAD.get());
				tabData.accept(FossilMinecraftModItems.ALIO_BODY.get());
				tabData.accept(FossilMinecraftModItems.ALIO_ARMS.get());
				tabData.accept(FossilMinecraftModItems.ALIO_LEGS.get());
				tabData.accept(FossilMinecraftModItems.SIAMO_HEAD.get());
				tabData.accept(FossilMinecraftModItems.SIAMO_BODY.get());
				tabData.accept(FossilMinecraftModItems.SIAMO_ARMS.get());
				tabData.accept(FossilMinecraftModItems.SIAMO_LEGS.get());
				tabData.accept(FossilMinecraftModItems.TREX_HEAD_BLANK.get());
				tabData.accept(FossilMinecraftModItems.TREX_BODY_BLANK.get());
				tabData.accept(FossilMinecraftModItems.TREX_ARMS_BLANK.get());
				tabData.accept(FossilMinecraftModItems.TREX_LEGS_BLANK.get());
				tabData.accept(FossilMinecraftModItems.DASPLETO_HEAD_BLANK.get());
				tabData.accept(FossilMinecraftModItems.DASPLETO_BODY_BLANK.get());
				tabData.accept(FossilMinecraftModItems.DASPLETO_ARMS_BLANK.get());
				tabData.accept(FossilMinecraftModItems.DASPLETO_LEGS_BLANK.get());
				tabData.accept(FossilMinecraftModItems.GORGO_HEAD_BLANK.get());
				tabData.accept(FossilMinecraftModItems.GORGO_BODY_BLANK.get());
				tabData.accept(FossilMinecraftModItems.GORGO_ARMS_BLANK.get());
				tabData.accept(FossilMinecraftModItems.GORGO_LEGS_BLANK.get());
				tabData.accept(FossilMinecraftModItems.TARBO_HEAD_BLANK.get());
				tabData.accept(FossilMinecraftModItems.TARBO_BODY_BLANK.get());
				tabData.accept(FossilMinecraftModItems.TARBO_ARMS_BLANK.get());
				tabData.accept(FossilMinecraftModItems.TARBO_LEGS_BLANK.get());
				tabData.accept(FossilMinecraftModItems.ALIO_HEAD_BLANK.get());
				tabData.accept(FossilMinecraftModItems.ALIO_BODY_BLANK.get());
				tabData.accept(FossilMinecraftModItems.ALIO_ARMS_BLANK.get());
				tabData.accept(FossilMinecraftModItems.ALIO_LEGS_BLANK.get());
				tabData.accept(FossilMinecraftModItems.SIAMO_HEAD_BLANK.get());
				tabData.accept(FossilMinecraftModItems.SIAMO_BODY_BLANK.get());
				tabData.accept(FossilMinecraftModItems.SIAMO_ARMS_BLANK.get());
				tabData.accept(FossilMinecraftModItems.SIAMO_LEGS_BLANK.get());
				tabData.accept(FossilMinecraftModItems.ALECTRO_HEAD.get());
				tabData.accept(FossilMinecraftModItems.ALECTRO_BODY.get());
				tabData.accept(FossilMinecraftModItems.ALECTRO_ARMS.get());
				tabData.accept(FossilMinecraftModItems.ALECTRO_LEGS.get());
				tabData.accept(FossilMinecraftModItems.ALECTRO_HEAD_BLANK.get());
				tabData.accept(FossilMinecraftModItems.ALECTRO_BODY_BLANK.get());
				tabData.accept(FossilMinecraftModItems.ALECTRO_ARMS_BLANK.get());
				tabData.accept(FossilMinecraftModItems.ALECTRO_LEGS_BLANK.get());
				tabData.accept(FossilMinecraftModItems.GUAN_HEAD.get());
				tabData.accept(FossilMinecraftModItems.GUAN_BODY.get());
				tabData.accept(FossilMinecraftModItems.GUAN_ARMS.get());
				tabData.accept(FossilMinecraftModItems.GUAN_LEGS.get());
				tabData.accept(FossilMinecraftModItems.GUAN_HEAD_BLANK.get());
				tabData.accept(FossilMinecraftModItems.GUAN_BODY_BLANK.get());
				tabData.accept(FossilMinecraftModItems.GUAN_ARMS_BLANK.get());
				tabData.accept(FossilMinecraftModItems.GUAN_LEGS_BLANK.get());
				tabData.accept(FossilMinecraftModItems.SHANSHAN_BODY.get());
				tabData.accept(FossilMinecraftModItems.SHANSHAN_ARMS.get());
				tabData.accept(FossilMinecraftModItems.SHANSHAN_LEGS.get());
				tabData.accept(FossilMinecraftModItems.SHANSHAN_HEAD_BLANK.get());
				tabData.accept(FossilMinecraftModItems.SHANSHAN_BODY_BLANK.get());
				tabData.accept(FossilMinecraftModItems.SHANSHAN_ARMS_BLANK.get());
				tabData.accept(FossilMinecraftModItems.SHANSHAN_LEGS_BLANK.get());
				tabData.accept(FossilMinecraftModItems.ALLO_HEAD.get());
				tabData.accept(FossilMinecraftModItems.ALLO_BODY.get());
				tabData.accept(FossilMinecraftModItems.ALLO_ARMS.get());
				tabData.accept(FossilMinecraftModItems.ALLO_LEGS.get());
				tabData.accept(FossilMinecraftModItems.ALLO_HEAD_BLANK.get());
				tabData.accept(FossilMinecraftModItems.ALLO_BODY_BLANK.get());
				tabData.accept(FossilMinecraftModItems.ALLO_ARMS_BLANK.get());
				tabData.accept(FossilMinecraftModItems.ALLO_LEGS_BLANK.get());
				tabData.accept(FossilMinecraftModItems.METRIA_HEAD.get());
				tabData.accept(FossilMinecraftModItems.METRIA_BODY.get());
				tabData.accept(FossilMinecraftModItems.METRIA_ARMS.get());
				tabData.accept(FossilMinecraftModItems.METRIA_LEGS.get());
				tabData.accept(FossilMinecraftModItems.METRIA_HEAD_BLANK.get());
				tabData.accept(FossilMinecraftModItems.METRIA_BODY_BLANK.get());
				tabData.accept(FossilMinecraftModItems.METRIA_ARMS_BLANK.get());
				tabData.accept(FossilMinecraftModItems.METRIA_LEGS_BLANK.get());
				tabData.accept(FossilMinecraftModItems.MEGALO_HEAD.get());
				tabData.accept(FossilMinecraftModItems.MEGALO_BODY.get());
				tabData.accept(FossilMinecraftModItems.MEGALO_ARMS.get());
				tabData.accept(FossilMinecraftModItems.MEGALO_LEGS.get());
				tabData.accept(FossilMinecraftModItems.MEGALO_HEAD_BLANK.get());
				tabData.accept(FossilMinecraftModItems.MEGALO_BODY_BLANK.get());
				tabData.accept(FossilMinecraftModItems.MEGALO_ARMS_BLANK.get());
				tabData.accept(FossilMinecraftModItems.MEGALO_LEGS_BLANK.get());
				tabData.accept(FossilMinecraftModItems.VENATOR_HEAD.get());
				tabData.accept(FossilMinecraftModItems.VENTATOR_BODY.get());
				tabData.accept(FossilMinecraftModItems.VENATOR_ARMS.get());
				tabData.accept(FossilMinecraftModItems.VENATOR_LEGS.get());
				tabData.accept(FossilMinecraftModItems.VENATOR_HEAD_BLANK.get());
				tabData.accept(FossilMinecraftModItems.VENATOR_BODY_BLANK.get());
				tabData.accept(FossilMinecraftModItems.VENATOR_ARMS_BLANK.get());
				tabData.accept(FossilMinecraftModItems.VENATOR_LEGS_BLANK.get());
				tabData.accept(FossilMinecraftModItems.S_RAPTOR_HEAD.get());
				tabData.accept(FossilMinecraftModItems.S_RAPTOR_BODY.get());
				tabData.accept(FossilMinecraftModItems.S_RAPTOR_ARMS.get());
				tabData.accept(FossilMinecraftModItems.S_RAPTOR_LEGS.get());
				tabData.accept(FossilMinecraftModItems.S_RAPTOR_HEAD_BLANK.get());
				tabData.accept(FossilMinecraftModItems.S_RAPTOR_BODY_BLANK.get());
				tabData.accept(FossilMinecraftModItems.S_RAPTOR_ARMS_BLANK.get());
				tabData.accept(FossilMinecraftModItems.S_RAPTOR_LEGS_BLANK.get());
				tabData.accept(FossilMinecraftModItems.GIGANTO_HEAD.get());
				tabData.accept(FossilMinecraftModItems.GIGANTO_BODY.get());
				tabData.accept(FossilMinecraftModItems.GIGANTO_ARMS.get());
				tabData.accept(FossilMinecraftModItems.GIGANTO_LEGS.get());
				tabData.accept(FossilMinecraftModItems.GIGANTO_HEAD_BLANK.get());
				tabData.accept(FossilMinecraftModItems.GIGANTO_BODY_BLANK.get());
				tabData.accept(FossilMinecraftModItems.GIGANTO_ARMS_BLANK.get());
				tabData.accept(FossilMinecraftModItems.GIGANTO_LEGS_BLANK.get());
				tabData.accept(FossilMinecraftModItems.CRYO_HEAD.get());
				tabData.accept(FossilMinecraftModItems.CRYO_BODY.get());
				tabData.accept(FossilMinecraftModItems.CRYO_ARMS.get());
				tabData.accept(FossilMinecraftModItems.CRYO_LEGS.get());
				tabData.accept(FossilMinecraftModItems.CRYO_HEAD_BLANK.get());
				tabData.accept(FossilMinecraftModItems.CRYO_BODY_BLANK.get());
				tabData.accept(FossilMinecraftModItems.CRYO_ARMS_BLANK.get());
				tabData.accept(FossilMinecraftModItems.CRYO_LEGS_BLANK.get());
				tabData.accept(FossilMinecraftModItems.CARCHAR_HEAD.get());
				tabData.accept(FossilMinecraftModItems.CARCHAR_BODY.get());
				tabData.accept(FossilMinecraftModItems.CARCHAR_ARMS.get());
				tabData.accept(FossilMinecraftModItems.CARCHAR_LEGS.get());
				tabData.accept(FossilMinecraftModItems.CARCHAR_HEAD_BLANK.get());
				tabData.accept(FossilMinecraftModItems.CARCHAR_BODY_BLANK.get());
				tabData.accept(FossilMinecraftModItems.CARCHAR_ARMS_BLANK.get());
				tabData.accept(FossilMinecraftModItems.CARCHAR_LEGS_BLANK.get());
				tabData.accept(FossilMinecraftModItems.ACRO_HEAD.get());
				tabData.accept(FossilMinecraftModItems.ACRO_BODY.get());
				tabData.accept(FossilMinecraftModItems.ACRO_ARMS.get());
				tabData.accept(FossilMinecraftModItems.ACRO_LEGS.get());
				tabData.accept(FossilMinecraftModItems.ACRO_HEAD_BLANK.get());
				tabData.accept(FossilMinecraftModItems.ACRO_BODY_BLANK.get());
				tabData.accept(FossilMinecraftModItems.ACRO_ARMS_BLANK.get());
				tabData.accept(FossilMinecraftModItems.ACRO_LEGS_BLANK.get());
				tabData.accept(FossilMinecraftModItems.F_RAPTOR_HEAD.get());
				tabData.accept(FossilMinecraftModItems.F_RAPTOR_BODY.get());
				tabData.accept(FossilMinecraftModItems.F_RAPTOR_ARMS.get());
				tabData.accept(FossilMinecraftModItems.F_RAPTOR_LEGS.get());
				tabData.accept(FossilMinecraftModItems.F_RAPTOR_HEAD_BLANK.get());
				tabData.accept(FossilMinecraftModItems.F_RAPTOR_BODY_BLANK.get());
				tabData.accept(FossilMinecraftModItems.F_RAPTOR_ARMS_BLANK.get());
				tabData.accept(FossilMinecraftModItems.F_RAPTOR_LEGS_BLANK.get());
				tabData.accept(FossilMinecraftModItems.SPINAX_HEAD.get());
				tabData.accept(FossilMinecraftModItems.SPINAX_BODY.get());
				tabData.accept(FossilMinecraftModItems.SPINAX_ARMS.get());
				tabData.accept(FossilMinecraftModItems.SPINAX_LEGS.get());
				tabData.accept(FossilMinecraftModItems.SPINAX_HEAD_BLANK.get());
				tabData.accept(FossilMinecraftModItems.SPINAX_BODY_BLANK.get());
				tabData.accept(FossilMinecraftModItems.SPINAX_ARMS_BLANK.get());
				tabData.accept(FossilMinecraftModItems.SPINAX_LEGS_BLANK.get());
				tabData.accept(FossilMinecraftModItems.NEO_HEAD.get());
				tabData.accept(FossilMinecraftModItems.NEO_BODY.get());
				tabData.accept(FossilMinecraftModItems.NEO_ARMS.get());
				tabData.accept(FossilMinecraftModItems.NEO_LEGS.get());
				tabData.accept(FossilMinecraftModItems.NEO_HEAD_BLANK.get());
				tabData.accept(FossilMinecraftModItems.NEO_BODY_BLANK.get());
				tabData.accept(FossilMinecraftModItems.NEO_ARMS_BLANK.get());
				tabData.accept(FossilMinecraftModItems.NEO_LEGS_BLANK.get());
				tabData.accept(FossilMinecraftModItems.COMPSO_HEAD.get());
				tabData.accept(FossilMinecraftModItems.COMPSO_BODY.get());
				tabData.accept(FossilMinecraftModItems.COMPSO_ARMS.get());
				tabData.accept(FossilMinecraftModItems.COMPSO_LEGS.get());
				tabData.accept(FossilMinecraftModItems.COMPSO_HEAD_BLANK.get());
				tabData.accept(FossilMinecraftModItems.COMPSO_BODY_BLANK.get());
				tabData.accept(FossilMinecraftModItems.COMPSO_ARMS_BLANK.get());
				tabData.accept(FossilMinecraftModItems.COMPSO_LEGS_BLANK.get());
				tabData.accept(FossilMinecraftModItems.SOPTERYX_HEAD.get());
				tabData.accept(FossilMinecraftModItems.SOPTERYX_BODY.get());
				tabData.accept(FossilMinecraftModItems.SOPTERYX_ARMS.get());
				tabData.accept(FossilMinecraftModItems.SOPTERYX_LEGS.get());
				tabData.accept(FossilMinecraftModItems.SOPTERYX_HEAD_BLANK.get());
				tabData.accept(FossilMinecraftModItems.SOPTERYX_BODY_BLANK.get());
				tabData.accept(FossilMinecraftModItems.SOPTERYX_ARMS_BLANK.get());
				tabData.accept(FossilMinecraftModItems.SOPTERYX_LEGS_BLANK.get());
				tabData.accept(FossilMinecraftModItems.DELTA_HEAD.get());
				tabData.accept(FossilMinecraftModItems.DELTA_BODY.get());
				tabData.accept(FossilMinecraftModItems.DELTA_ARMS.get());
				tabData.accept(FossilMinecraftModItems.DELTA_LEGS.get());
				tabData.accept(FossilMinecraftModItems.DELTA_HEAD_BLANK.get());
				tabData.accept(FossilMinecraftModItems.DELTA_BODY_BLANK.get());
				tabData.accept(FossilMinecraftModItems.DELTA_ARMS_BLANK.get());
				tabData.accept(FossilMinecraftModItems.DELTA_LEGS_BLANK.get());
				tabData.accept(FossilMinecraftModItems.TRO_HEAD.get());
				tabData.accept(FossilMinecraftModItems.TRO_BODY.get());
				tabData.accept(FossilMinecraftModItems.TRO_ARMS.get());
				tabData.accept(FossilMinecraftModItems.TRO_LEGS.get());
				tabData.accept(FossilMinecraftModItems.NYCHUS_HEAD.get());
				tabData.accept(FossilMinecraftModItems.NYCHUS_BODY.get());
				tabData.accept(FossilMinecraftModItems.NYCHUS_ARMS.get());
				tabData.accept(FossilMinecraftModItems.NYCHUS_LEGS.get());
				tabData.accept(FossilMinecraftModItems.NYCHUS_HEAD_BLANK.get());
				tabData.accept(FossilMinecraftModItems.NYCHUS_BODY_BLANK.get());
				tabData.accept(FossilMinecraftModItems.NYCHUS_ARMS_BLANK.get());
				tabData.accept(FossilMinecraftModItems.NYCHUS_LEGS_BLANK.get());
				tabData.accept(FossilMinecraftModItems.M_RAPTOR_HEAD.get());
				tabData.accept(FossilMinecraftModItems.M_RAPTOR_BODY.get());
				tabData.accept(FossilMinecraftModItems.M_RAPTOR_ARMS.get());
				tabData.accept(FossilMinecraftModItems.M_RAPTOR_LEGS.get());
				tabData.accept(FossilMinecraftModItems.M_RAPTOR_HEAD_BLANK.get());
				tabData.accept(FossilMinecraftModItems.M_RAPTOR_BODY_BLANK.get());
				tabData.accept(FossilMinecraftModItems.M_RAPTOR_ARMS_BLANK.get());
				tabData.accept(FossilMinecraftModItems.M_RAPTOR_LEGS_BLANK.get());
			}).withSearchBar().build());

	@SubscribeEvent
	public static void buildTabContentsVanilla(BuildCreativeModeTabContentsEvent tabData) {

		if (tabData.getTabKey() == CreativeModeTabs.SPAWN_EGGS) {
			tabData.accept(FossilMinecraftModItems.URAPTOR_SPAWN_EGG.get());
		}
	}
}
