
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.fossilminecraft.init;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.common.ForgeSpawnEggItem;

import net.minecraft.world.level.block.Block;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.BlockItem;

import net.mcreator.fossilminecraft.item.VraptorMedalItem;
import net.mcreator.fossilminecraft.item.VentatorBodyItem;
import net.mcreator.fossilminecraft.item.VenatorLegsItem;
import net.mcreator.fossilminecraft.item.VenatorLegsBlankItem;
import net.mcreator.fossilminecraft.item.VenatorHeadItem;
import net.mcreator.fossilminecraft.item.VenatorHeadBlankItem;
import net.mcreator.fossilminecraft.item.VenatorBodyBlankItem;
import net.mcreator.fossilminecraft.item.VenatorArmsItem;
import net.mcreator.fossilminecraft.item.VenatorArmsBlankItem;
import net.mcreator.fossilminecraft.item.UraptorMedalItem;
import net.mcreator.fossilminecraft.item.UnknownFossilItem;
import net.mcreator.fossilminecraft.item.TroLegsItem;
import net.mcreator.fossilminecraft.item.TroHeadItem;
import net.mcreator.fossilminecraft.item.TroBodyItem;
import net.mcreator.fossilminecraft.item.TroArmsItem;
import net.mcreator.fossilminecraft.item.TrexMedalItem;
import net.mcreator.fossilminecraft.item.TrexLegsItem;
import net.mcreator.fossilminecraft.item.TrexLegsBlankItem;
import net.mcreator.fossilminecraft.item.TrexHeadItem;
import net.mcreator.fossilminecraft.item.TrexHeadBlankItem;
import net.mcreator.fossilminecraft.item.TrexBodyItem;
import net.mcreator.fossilminecraft.item.TrexBodyBlankItem;
import net.mcreator.fossilminecraft.item.TrexArmsItem;
import net.mcreator.fossilminecraft.item.TrexArmsBlankItem;
import net.mcreator.fossilminecraft.item.TarboLegsItem;
import net.mcreator.fossilminecraft.item.TarboLegsBlankItem;
import net.mcreator.fossilminecraft.item.TarboHeadItem;
import net.mcreator.fossilminecraft.item.TarboHeadBlankItem;
import net.mcreator.fossilminecraft.item.TarboBodyItem;
import net.mcreator.fossilminecraft.item.TarboBodyBlankItem;
import net.mcreator.fossilminecraft.item.TarboArmsItem;
import net.mcreator.fossilminecraft.item.TarboArmsBlankItem;
import net.mcreator.fossilminecraft.item.SuperHammerItem;
import net.mcreator.fossilminecraft.item.SpinaxLegsItem;
import net.mcreator.fossilminecraft.item.SpinaxLegsBlankItem;
import net.mcreator.fossilminecraft.item.SpinaxHeadItem;
import net.mcreator.fossilminecraft.item.SpinaxHeadBlankItem;
import net.mcreator.fossilminecraft.item.SpinaxBodyItem;
import net.mcreator.fossilminecraft.item.SpinaxBodyBlankItem;
import net.mcreator.fossilminecraft.item.SpinaxArmsItem;
import net.mcreator.fossilminecraft.item.SpinaxArmsBlankItem;
import net.mcreator.fossilminecraft.item.SopteryxLegsItem;
import net.mcreator.fossilminecraft.item.SopteryxLegsBlankItem;
import net.mcreator.fossilminecraft.item.SopteryxHeadItem;
import net.mcreator.fossilminecraft.item.SopteryxHeadBlankItem;
import net.mcreator.fossilminecraft.item.SopteryxBodyItem;
import net.mcreator.fossilminecraft.item.SopteryxBodyBlankItem;
import net.mcreator.fossilminecraft.item.SopteryxArmsItem;
import net.mcreator.fossilminecraft.item.SopteryxArmsBlankItem;
import net.mcreator.fossilminecraft.item.SonarItem;
import net.mcreator.fossilminecraft.item.SiamoLegsItem;
import net.mcreator.fossilminecraft.item.SiamoLegsBlankItem;
import net.mcreator.fossilminecraft.item.SiamoHeadItem;
import net.mcreator.fossilminecraft.item.SiamoHeadBlankItem;
import net.mcreator.fossilminecraft.item.SiamoBodyItem;
import net.mcreator.fossilminecraft.item.SiamoBodyBlankItem;
import net.mcreator.fossilminecraft.item.SiamoArmsItem;
import net.mcreator.fossilminecraft.item.SiamoArmsBlankItem;
import net.mcreator.fossilminecraft.item.ShanshanMedalItem;
import net.mcreator.fossilminecraft.item.ShanshanLegsItem;
import net.mcreator.fossilminecraft.item.ShanshanLegsBlankItem;
import net.mcreator.fossilminecraft.item.ShanshanHeadItem;
import net.mcreator.fossilminecraft.item.ShanshanHeadBlankItem;
import net.mcreator.fossilminecraft.item.ShanshanFossilItem;
import net.mcreator.fossilminecraft.item.ShanshanBodyItem;
import net.mcreator.fossilminecraft.item.ShanshanBodyBlankItem;
import net.mcreator.fossilminecraft.item.ShanshanArmsItem;
import net.mcreator.fossilminecraft.item.ShanshanArmsBlankItem;
import net.mcreator.fossilminecraft.item.SeidonMedalItem;
import net.mcreator.fossilminecraft.item.SeidonHeadItem;
import net.mcreator.fossilminecraft.item.SeidonHeadFossilItem;
import net.mcreator.fossilminecraft.item.SRaptorLegsItem;
import net.mcreator.fossilminecraft.item.SRaptorLegsBlankItem;
import net.mcreator.fossilminecraft.item.SRaptorHeadItem;
import net.mcreator.fossilminecraft.item.SRaptorHeadBlankItem;
import net.mcreator.fossilminecraft.item.SRaptorBodyItem;
import net.mcreator.fossilminecraft.item.SRaptorBodyBlankItem;
import net.mcreator.fossilminecraft.item.SRaptorArmsItem;
import net.mcreator.fossilminecraft.item.SRaptorArmsBlankItem;
import net.mcreator.fossilminecraft.item.NychusLegsItem;
import net.mcreator.fossilminecraft.item.NychusLegsBlankItem;
import net.mcreator.fossilminecraft.item.NychusHeadItem;
import net.mcreator.fossilminecraft.item.NychusHeadBlankItem;
import net.mcreator.fossilminecraft.item.NychusBodyItem;
import net.mcreator.fossilminecraft.item.NychusBodyBlankItem;
import net.mcreator.fossilminecraft.item.NychusArmsItem;
import net.mcreator.fossilminecraft.item.NychusArmsBlankItem;
import net.mcreator.fossilminecraft.item.NeoLegsItem;
import net.mcreator.fossilminecraft.item.NeoLegsBlankItem;
import net.mcreator.fossilminecraft.item.NeoHeadItem;
import net.mcreator.fossilminecraft.item.NeoHeadBlankItem;
import net.mcreator.fossilminecraft.item.NeoBodyItem;
import net.mcreator.fossilminecraft.item.NeoBodyBlankItem;
import net.mcreator.fossilminecraft.item.NeoArmsItem;
import net.mcreator.fossilminecraft.item.NeoArmsBlankItem;
import net.mcreator.fossilminecraft.item.MetriaLegsItem;
import net.mcreator.fossilminecraft.item.MetriaLegsBlankItem;
import net.mcreator.fossilminecraft.item.MetriaHeadItem;
import net.mcreator.fossilminecraft.item.MetriaHeadBlankItem;
import net.mcreator.fossilminecraft.item.MetriaBodyItem;
import net.mcreator.fossilminecraft.item.MetriaBodyBlankItem;
import net.mcreator.fossilminecraft.item.MetriaArmsItem;
import net.mcreator.fossilminecraft.item.MetriaArmsBlankItem;
import net.mcreator.fossilminecraft.item.MegaloLegsItem;
import net.mcreator.fossilminecraft.item.MegaloLegsBlankItem;
import net.mcreator.fossilminecraft.item.MegaloHeadItem;
import net.mcreator.fossilminecraft.item.MegaloHeadBlankItem;
import net.mcreator.fossilminecraft.item.MegaloBodyItem;
import net.mcreator.fossilminecraft.item.MegaloBodyBlankItem;
import net.mcreator.fossilminecraft.item.MegaloArmsItem;
import net.mcreator.fossilminecraft.item.MegaloArmsBlankItem;
import net.mcreator.fossilminecraft.item.MRaptorLegsItem;
import net.mcreator.fossilminecraft.item.MRaptorLegsBlankItem;
import net.mcreator.fossilminecraft.item.MRaptorHeadItem;
import net.mcreator.fossilminecraft.item.MRaptorHeadBlankItem;
import net.mcreator.fossilminecraft.item.MRaptorBodyItem;
import net.mcreator.fossilminecraft.item.MRaptorBodyBlankItem;
import net.mcreator.fossilminecraft.item.MRaptorArmsItem;
import net.mcreator.fossilminecraft.item.MRaptorArmsBlankItem;
import net.mcreator.fossilminecraft.item.HammerItem;
import net.mcreator.fossilminecraft.item.GuanLegsItem;
import net.mcreator.fossilminecraft.item.GuanLegsBlankItem;
import net.mcreator.fossilminecraft.item.GuanHeadItem;
import net.mcreator.fossilminecraft.item.GuanHeadBlankItem;
import net.mcreator.fossilminecraft.item.GuanBodyItem;
import net.mcreator.fossilminecraft.item.GuanBodyBlankItem;
import net.mcreator.fossilminecraft.item.GuanArmsItem;
import net.mcreator.fossilminecraft.item.GuanArmsBlankItem;
import net.mcreator.fossilminecraft.item.GorgoLegsItem;
import net.mcreator.fossilminecraft.item.GorgoLegsBlankItem;
import net.mcreator.fossilminecraft.item.GorgoHeadItem;
import net.mcreator.fossilminecraft.item.GorgoHeadBlankItem;
import net.mcreator.fossilminecraft.item.GorgoBodyItem;
import net.mcreator.fossilminecraft.item.GorgoBodyBlankItem;
import net.mcreator.fossilminecraft.item.GorgoArmsItem;
import net.mcreator.fossilminecraft.item.GorgoArmsBlankItem;
import net.mcreator.fossilminecraft.item.GigantoLegsItem;
import net.mcreator.fossilminecraft.item.GigantoLegsBlankItem;
import net.mcreator.fossilminecraft.item.GigantoHeadItem;
import net.mcreator.fossilminecraft.item.GigantoHeadBlankItem;
import net.mcreator.fossilminecraft.item.GigantoBodyItem;
import net.mcreator.fossilminecraft.item.GigantoBodyBlankItem;
import net.mcreator.fossilminecraft.item.GigantoArmsItem;
import net.mcreator.fossilminecraft.item.GigantoArmsBlankItem;
import net.mcreator.fossilminecraft.item.FRaptorLegsItem;
import net.mcreator.fossilminecraft.item.FRaptorLegsBlankItem;
import net.mcreator.fossilminecraft.item.FRaptorHeadItem;
import net.mcreator.fossilminecraft.item.FRaptorHeadBlankItem;
import net.mcreator.fossilminecraft.item.FRaptorBodyItem;
import net.mcreator.fossilminecraft.item.FRaptorBodyBlankItem;
import net.mcreator.fossilminecraft.item.FRaptorArmsItem;
import net.mcreator.fossilminecraft.item.FRaptorArmsBlankItem;
import net.mcreator.fossilminecraft.item.EmptyMedalItem;
import net.mcreator.fossilminecraft.item.DrillItem;
import net.mcreator.fossilminecraft.item.DeltaLegsItem;
import net.mcreator.fossilminecraft.item.DeltaLegsBlankItem;
import net.mcreator.fossilminecraft.item.DeltaHeadItem;
import net.mcreator.fossilminecraft.item.DeltaHeadBlankItem;
import net.mcreator.fossilminecraft.item.DeltaBodyItem;
import net.mcreator.fossilminecraft.item.DeltaBodyBlankItem;
import net.mcreator.fossilminecraft.item.DeltaArmsItem;
import net.mcreator.fossilminecraft.item.DeltaArmsBlankItem;
import net.mcreator.fossilminecraft.item.DaspletoLegsItem;
import net.mcreator.fossilminecraft.item.DaspletoLegsBlankItem;
import net.mcreator.fossilminecraft.item.DaspletoHeadItem;
import net.mcreator.fossilminecraft.item.DaspletoHeadBlankItem;
import net.mcreator.fossilminecraft.item.DaspletoBodyItem;
import net.mcreator.fossilminecraft.item.DaspletoBodyBlankItem;
import net.mcreator.fossilminecraft.item.DaspletoArmsItem;
import net.mcreator.fossilminecraft.item.DaspletoArmsBlankItem;
import net.mcreator.fossilminecraft.item.CryoLegsItem;
import net.mcreator.fossilminecraft.item.CryoLegsBlankItem;
import net.mcreator.fossilminecraft.item.CryoHeadItem;
import net.mcreator.fossilminecraft.item.CryoHeadBlankItem;
import net.mcreator.fossilminecraft.item.CryoBodyItem;
import net.mcreator.fossilminecraft.item.CryoBodyBlankItem;
import net.mcreator.fossilminecraft.item.CryoArmsItem;
import net.mcreator.fossilminecraft.item.CryoArmsBlankItem;
import net.mcreator.fossilminecraft.item.CompsoLegsItem;
import net.mcreator.fossilminecraft.item.CompsoLegsBlankItem;
import net.mcreator.fossilminecraft.item.CompsoHeadItem;
import net.mcreator.fossilminecraft.item.CompsoHeadBlankItem;
import net.mcreator.fossilminecraft.item.CompsoBodyItem;
import net.mcreator.fossilminecraft.item.CompsoBodyBlankItem;
import net.mcreator.fossilminecraft.item.CompsoArmsItem;
import net.mcreator.fossilminecraft.item.CompsoArmsBlankItem;
import net.mcreator.fossilminecraft.item.CarcharLegsItem;
import net.mcreator.fossilminecraft.item.CarcharLegsBlankItem;
import net.mcreator.fossilminecraft.item.CarcharHeadItem;
import net.mcreator.fossilminecraft.item.CarcharHeadBlankItem;
import net.mcreator.fossilminecraft.item.CarcharBodyItem;
import net.mcreator.fossilminecraft.item.CarcharBodyBlankItem;
import net.mcreator.fossilminecraft.item.CarcharArmsItem;
import net.mcreator.fossilminecraft.item.CarcharArmsBlankItem;
import net.mcreator.fossilminecraft.item.AlloLegsItem;
import net.mcreator.fossilminecraft.item.AlloLegsBlankItem;
import net.mcreator.fossilminecraft.item.AlloHeadItem;
import net.mcreator.fossilminecraft.item.AlloHeadBlankItem;
import net.mcreator.fossilminecraft.item.AlloBodyItem;
import net.mcreator.fossilminecraft.item.AlloBodyBlankItem;
import net.mcreator.fossilminecraft.item.AlloArmsItem;
import net.mcreator.fossilminecraft.item.AlloArmsBlankItem;
import net.mcreator.fossilminecraft.item.AlioLegsItem;
import net.mcreator.fossilminecraft.item.AlioLegsBlankItem;
import net.mcreator.fossilminecraft.item.AlioHeadItem;
import net.mcreator.fossilminecraft.item.AlioHeadBlankItem;
import net.mcreator.fossilminecraft.item.AlioBodyItem;
import net.mcreator.fossilminecraft.item.AlioBodyBlankItem;
import net.mcreator.fossilminecraft.item.AlioArmsItem;
import net.mcreator.fossilminecraft.item.AlioArmsBlankItem;
import net.mcreator.fossilminecraft.item.AlectroLegsItem;
import net.mcreator.fossilminecraft.item.AlectroLegsBlankItem;
import net.mcreator.fossilminecraft.item.AlectroHeadItem;
import net.mcreator.fossilminecraft.item.AlectroHeadBlankItem;
import net.mcreator.fossilminecraft.item.AlectroBodyItem;
import net.mcreator.fossilminecraft.item.AlectroBodyBlankItem;
import net.mcreator.fossilminecraft.item.AlectroArmsItem;
import net.mcreator.fossilminecraft.item.AlectroArmsBlankItem;
import net.mcreator.fossilminecraft.item.AcroLegsItem;
import net.mcreator.fossilminecraft.item.AcroLegsBlankItem;
import net.mcreator.fossilminecraft.item.AcroHeadItem;
import net.mcreator.fossilminecraft.item.AcroHeadBlankItem;
import net.mcreator.fossilminecraft.item.AcroBodyItem;
import net.mcreator.fossilminecraft.item.AcroBodyBlankItem;
import net.mcreator.fossilminecraft.item.AcroArmsItem;
import net.mcreator.fossilminecraft.item.AcroArmsBlankItem;
import net.mcreator.fossilminecraft.FossilMinecraftMod;

public class FossilMinecraftModItems {
	public static final DeferredRegister<Item> REGISTRY = DeferredRegister.create(ForgeRegistries.ITEMS, FossilMinecraftMod.MODID);
	public static final RegistryObject<Item> TREX_SPAWN_EGG = REGISTRY.register("trex_spawn_egg", () -> new ForgeSpawnEggItem(FossilMinecraftModEntities.TREX, -52429, -13421773, new Item.Properties()));
	public static final RegistryObject<Item> SHAN_SHAN_SPAWN_EGG = REGISTRY.register("shan_shan_spawn_egg", () -> new ForgeSpawnEggItem(FossilMinecraftModEntities.SHAN_SHAN, -52327, -205, new Item.Properties()));
	public static final RegistryObject<Item> VRAPTOR_SPAWN_EGG = REGISTRY.register("vraptor_spawn_egg", () -> new ForgeSpawnEggItem(FossilMinecraftModEntities.VRAPTOR, -16711783, -1, new Item.Properties()));
	public static final RegistryObject<Item> TREX_MEDAL = REGISTRY.register("trex_medal", () -> new TrexMedalItem());
	public static final RegistryObject<Item> SHANSHAN_MEDAL = REGISTRY.register("shanshan_medal", () -> new ShanshanMedalItem());
	public static final RegistryObject<Item> VRAPTOR_MEDAL = REGISTRY.register("vraptor_medal", () -> new VraptorMedalItem());
	public static final RegistryObject<Item> SEIDON_SPAWN_EGG = REGISTRY.register("seidon_spawn_egg", () -> new ForgeSpawnEggItem(FossilMinecraftModEntities.SEIDON, -16724737, -1, new Item.Properties()));
	public static final RegistryObject<Item> SEIDON_MEDAL = REGISTRY.register("seidon_medal", () -> new SeidonMedalItem());
	public static final RegistryObject<Item> CLEANER = block(FossilMinecraftModBlocks.CLEANER);
	public static final RegistryObject<Item> UNKNOWN_FOSSIL = REGISTRY.register("unknown_fossil", () -> new UnknownFossilItem());
	public static final RegistryObject<Item> SHANSHAN_FOSSIL = REGISTRY.register("shanshan_fossil", () -> new ShanshanFossilItem());
	public static final RegistryObject<Item> REVIVER = block(FossilMinecraftModBlocks.REVIVER);
	public static final RegistryObject<Item> FOSSIL = block(FossilMinecraftModBlocks.FOSSIL);
	public static final RegistryObject<Item> TREX_HEAD = REGISTRY.register("trex_head", () -> new TrexHeadItem());
	public static final RegistryObject<Item> SHANSHAN_HEAD = REGISTRY.register("shanshan_head", () -> new ShanshanHeadItem());
	public static final RegistryObject<Item> EMPTY_MEDAL = REGISTRY.register("empty_medal", () -> new EmptyMedalItem());
	public static final RegistryObject<Item> DRILL = REGISTRY.register("drill", () -> new DrillItem());
	public static final RegistryObject<Item> HAMMER = REGISTRY.register("hammer", () -> new HammerItem());
	public static final RegistryObject<Item> SUPER_HAMMER = REGISTRY.register("super_hammer", () -> new SuperHammerItem());
	public static final RegistryObject<Item> URAPTOR_SPAWN_EGG = REGISTRY.register("uraptor_spawn_egg", () -> new ForgeSpawnEggItem(FossilMinecraftModEntities.URAPTOR, -39322, -16764058, new Item.Properties()));
	public static final RegistryObject<Item> SONAR = REGISTRY.register("sonar", () -> new SonarItem());
	public static final RegistryObject<Item> SEIDON_HEAD = REGISTRY.register("seidon_head", () -> new SeidonHeadItem());
	public static final RegistryObject<Item> URAPTOR_MEDAL = REGISTRY.register("uraptor_medal", () -> new UraptorMedalItem());
	public static final RegistryObject<Item> SEIDON_HEAD_FOSSIL = REGISTRY.register("seidon_head_fossil", () -> new SeidonHeadFossilItem());
	public static final RegistryObject<Item> TREX_BODY = REGISTRY.register("trex_body", () -> new TrexBodyItem());
	public static final RegistryObject<Item> TREX_ARMS = REGISTRY.register("trex_arms", () -> new TrexArmsItem());
	public static final RegistryObject<Item> TREX_LEGS = REGISTRY.register("trex_legs", () -> new TrexLegsItem());
	public static final RegistryObject<Item> DASPLETO_HEAD = REGISTRY.register("daspleto_head", () -> new DaspletoHeadItem());
	public static final RegistryObject<Item> DASPLETO_BODY = REGISTRY.register("daspleto_body", () -> new DaspletoBodyItem());
	public static final RegistryObject<Item> DASPLETO_ARMS = REGISTRY.register("daspleto_arms", () -> new DaspletoArmsItem());
	public static final RegistryObject<Item> DASPLETO_LEGS = REGISTRY.register("daspleto_legs", () -> new DaspletoLegsItem());
	public static final RegistryObject<Item> GORGO_HEAD = REGISTRY.register("gorgo_head", () -> new GorgoHeadItem());
	public static final RegistryObject<Item> GORGO_BODY = REGISTRY.register("gorgo_body", () -> new GorgoBodyItem());
	public static final RegistryObject<Item> GORGO_ARMS = REGISTRY.register("gorgo_arms", () -> new GorgoArmsItem());
	public static final RegistryObject<Item> GORGO_LEGS = REGISTRY.register("gorgo_legs", () -> new GorgoLegsItem());
	public static final RegistryObject<Item> TARBO_HEAD = REGISTRY.register("tarbo_head", () -> new TarboHeadItem());
	public static final RegistryObject<Item> TARBO_BODY = REGISTRY.register("tarbo_body", () -> new TarboBodyItem());
	public static final RegistryObject<Item> TARBO_ARMS = REGISTRY.register("tarbo_arms", () -> new TarboArmsItem());
	public static final RegistryObject<Item> TARBO_LEGS = REGISTRY.register("tarbo_legs", () -> new TarboLegsItem());
	public static final RegistryObject<Item> ALIO_HEAD = REGISTRY.register("alio_head", () -> new AlioHeadItem());
	public static final RegistryObject<Item> ALIO_BODY = REGISTRY.register("alio_body", () -> new AlioBodyItem());
	public static final RegistryObject<Item> ALIO_ARMS = REGISTRY.register("alio_arms", () -> new AlioArmsItem());
	public static final RegistryObject<Item> ALIO_LEGS = REGISTRY.register("alio_legs", () -> new AlioLegsItem());
	public static final RegistryObject<Item> SIAMO_HEAD = REGISTRY.register("siamo_head", () -> new SiamoHeadItem());
	public static final RegistryObject<Item> SIAMO_BODY = REGISTRY.register("siamo_body", () -> new SiamoBodyItem());
	public static final RegistryObject<Item> SIAMO_ARMS = REGISTRY.register("siamo_arms", () -> new SiamoArmsItem());
	public static final RegistryObject<Item> SIAMO_LEGS = REGISTRY.register("siamo_legs", () -> new SiamoLegsItem());
	public static final RegistryObject<Item> TREX_HEAD_BLANK = REGISTRY.register("trex_head_blank", () -> new TrexHeadBlankItem());
	public static final RegistryObject<Item> TREX_BODY_BLANK = REGISTRY.register("trex_body_blank", () -> new TrexBodyBlankItem());
	public static final RegistryObject<Item> TREX_ARMS_BLANK = REGISTRY.register("trex_arms_blank", () -> new TrexArmsBlankItem());
	public static final RegistryObject<Item> TREX_LEGS_BLANK = REGISTRY.register("trex_legs_blank", () -> new TrexLegsBlankItem());
	public static final RegistryObject<Item> DASPLETO_HEAD_BLANK = REGISTRY.register("daspleto_head_blank", () -> new DaspletoHeadBlankItem());
	public static final RegistryObject<Item> DASPLETO_BODY_BLANK = REGISTRY.register("daspleto_body_blank", () -> new DaspletoBodyBlankItem());
	public static final RegistryObject<Item> DASPLETO_ARMS_BLANK = REGISTRY.register("daspleto_arms_blank", () -> new DaspletoArmsBlankItem());
	public static final RegistryObject<Item> DASPLETO_LEGS_BLANK = REGISTRY.register("daspleto_legs_blank", () -> new DaspletoLegsBlankItem());
	public static final RegistryObject<Item> GORGO_HEAD_BLANK = REGISTRY.register("gorgo_head_blank", () -> new GorgoHeadBlankItem());
	public static final RegistryObject<Item> GORGO_BODY_BLANK = REGISTRY.register("gorgo_body_blank", () -> new GorgoBodyBlankItem());
	public static final RegistryObject<Item> GORGO_ARMS_BLANK = REGISTRY.register("gorgo_arms_blank", () -> new GorgoArmsBlankItem());
	public static final RegistryObject<Item> GORGO_LEGS_BLANK = REGISTRY.register("gorgo_legs_blank", () -> new GorgoLegsBlankItem());
	public static final RegistryObject<Item> TARBO_HEAD_BLANK = REGISTRY.register("tarbo_head_blank", () -> new TarboHeadBlankItem());
	public static final RegistryObject<Item> TARBO_BODY_BLANK = REGISTRY.register("tarbo_body_blank", () -> new TarboBodyBlankItem());
	public static final RegistryObject<Item> TARBO_ARMS_BLANK = REGISTRY.register("tarbo_arms_blank", () -> new TarboArmsBlankItem());
	public static final RegistryObject<Item> TARBO_LEGS_BLANK = REGISTRY.register("tarbo_legs_blank", () -> new TarboLegsBlankItem());
	public static final RegistryObject<Item> ALIO_HEAD_BLANK = REGISTRY.register("alio_head_blank", () -> new AlioHeadBlankItem());
	public static final RegistryObject<Item> ALIO_BODY_BLANK = REGISTRY.register("alio_body_blank", () -> new AlioBodyBlankItem());
	public static final RegistryObject<Item> ALIO_ARMS_BLANK = REGISTRY.register("alio_arms_blank", () -> new AlioArmsBlankItem());
	public static final RegistryObject<Item> ALIO_LEGS_BLANK = REGISTRY.register("alio_legs_blank", () -> new AlioLegsBlankItem());
	public static final RegistryObject<Item> SIAMO_HEAD_BLANK = REGISTRY.register("siamo_head_blank", () -> new SiamoHeadBlankItem());
	public static final RegistryObject<Item> SIAMO_BODY_BLANK = REGISTRY.register("siamo_body_blank", () -> new SiamoBodyBlankItem());
	public static final RegistryObject<Item> SIAMO_ARMS_BLANK = REGISTRY.register("siamo_arms_blank", () -> new SiamoArmsBlankItem());
	public static final RegistryObject<Item> SIAMO_LEGS_BLANK = REGISTRY.register("siamo_legs_blank", () -> new SiamoLegsBlankItem());
	public static final RegistryObject<Item> ALECTRO_HEAD = REGISTRY.register("alectro_head", () -> new AlectroHeadItem());
	public static final RegistryObject<Item> ALECTRO_BODY = REGISTRY.register("alectro_body", () -> new AlectroBodyItem());
	public static final RegistryObject<Item> ALECTRO_ARMS = REGISTRY.register("alectro_arms", () -> new AlectroArmsItem());
	public static final RegistryObject<Item> ALECTRO_LEGS = REGISTRY.register("alectro_legs", () -> new AlectroLegsItem());
	public static final RegistryObject<Item> ALECTRO_HEAD_BLANK = REGISTRY.register("alectro_head_blank", () -> new AlectroHeadBlankItem());
	public static final RegistryObject<Item> ALECTRO_BODY_BLANK = REGISTRY.register("alectro_body_blank", () -> new AlectroBodyBlankItem());
	public static final RegistryObject<Item> ALECTRO_ARMS_BLANK = REGISTRY.register("alectro_arms_blank", () -> new AlectroArmsBlankItem());
	public static final RegistryObject<Item> ALECTRO_LEGS_BLANK = REGISTRY.register("alectro_legs_blank", () -> new AlectroLegsBlankItem());
	public static final RegistryObject<Item> GUAN_HEAD = REGISTRY.register("guan_head", () -> new GuanHeadItem());
	public static final RegistryObject<Item> GUAN_BODY = REGISTRY.register("guan_body", () -> new GuanBodyItem());
	public static final RegistryObject<Item> GUAN_ARMS = REGISTRY.register("guan_arms", () -> new GuanArmsItem());
	public static final RegistryObject<Item> GUAN_LEGS = REGISTRY.register("guan_legs", () -> new GuanLegsItem());
	public static final RegistryObject<Item> GUAN_HEAD_BLANK = REGISTRY.register("guan_head_blank", () -> new GuanHeadBlankItem());
	public static final RegistryObject<Item> GUAN_BODY_BLANK = REGISTRY.register("guan_body_blank", () -> new GuanBodyBlankItem());
	public static final RegistryObject<Item> GUAN_ARMS_BLANK = REGISTRY.register("guan_arms_blank", () -> new GuanArmsBlankItem());
	public static final RegistryObject<Item> GUAN_LEGS_BLANK = REGISTRY.register("guan_legs_blank", () -> new GuanLegsBlankItem());
	public static final RegistryObject<Item> SHANSHAN_BODY = REGISTRY.register("shanshan_body", () -> new ShanshanBodyItem());
	public static final RegistryObject<Item> SHANSHAN_ARMS = REGISTRY.register("shanshan_arms", () -> new ShanshanArmsItem());
	public static final RegistryObject<Item> SHANSHAN_LEGS = REGISTRY.register("shanshan_legs", () -> new ShanshanLegsItem());
	public static final RegistryObject<Item> SHANSHAN_HEAD_BLANK = REGISTRY.register("shanshan_head_blank", () -> new ShanshanHeadBlankItem());
	public static final RegistryObject<Item> SHANSHAN_BODY_BLANK = REGISTRY.register("shanshan_body_blank", () -> new ShanshanBodyBlankItem());
	public static final RegistryObject<Item> SHANSHAN_ARMS_BLANK = REGISTRY.register("shanshan_arms_blank", () -> new ShanshanArmsBlankItem());
	public static final RegistryObject<Item> SHANSHAN_LEGS_BLANK = REGISTRY.register("shanshan_legs_blank", () -> new ShanshanLegsBlankItem());
	public static final RegistryObject<Item> ALLO_HEAD = REGISTRY.register("allo_head", () -> new AlloHeadItem());
	public static final RegistryObject<Item> ALLO_BODY = REGISTRY.register("allo_body", () -> new AlloBodyItem());
	public static final RegistryObject<Item> ALLO_ARMS = REGISTRY.register("allo_arms", () -> new AlloArmsItem());
	public static final RegistryObject<Item> ALLO_LEGS = REGISTRY.register("allo_legs", () -> new AlloLegsItem());
	public static final RegistryObject<Item> ALLO_HEAD_BLANK = REGISTRY.register("allo_head_blank", () -> new AlloHeadBlankItem());
	public static final RegistryObject<Item> ALLO_BODY_BLANK = REGISTRY.register("allo_body_blank", () -> new AlloBodyBlankItem());
	public static final RegistryObject<Item> ALLO_ARMS_BLANK = REGISTRY.register("allo_arms_blank", () -> new AlloArmsBlankItem());
	public static final RegistryObject<Item> ALLO_LEGS_BLANK = REGISTRY.register("allo_legs_blank", () -> new AlloLegsBlankItem());
	public static final RegistryObject<Item> METRIA_HEAD = REGISTRY.register("metria_head", () -> new MetriaHeadItem());
	public static final RegistryObject<Item> METRIA_BODY = REGISTRY.register("metria_body", () -> new MetriaBodyItem());
	public static final RegistryObject<Item> METRIA_ARMS = REGISTRY.register("metria_arms", () -> new MetriaArmsItem());
	public static final RegistryObject<Item> METRIA_LEGS = REGISTRY.register("metria_legs", () -> new MetriaLegsItem());
	public static final RegistryObject<Item> METRIA_HEAD_BLANK = REGISTRY.register("metria_head_blank", () -> new MetriaHeadBlankItem());
	public static final RegistryObject<Item> METRIA_BODY_BLANK = REGISTRY.register("metria_body_blank", () -> new MetriaBodyBlankItem());
	public static final RegistryObject<Item> METRIA_ARMS_BLANK = REGISTRY.register("metria_arms_blank", () -> new MetriaArmsBlankItem());
	public static final RegistryObject<Item> METRIA_LEGS_BLANK = REGISTRY.register("metria_legs_blank", () -> new MetriaLegsBlankItem());
	public static final RegistryObject<Item> MEGALO_HEAD = REGISTRY.register("megalo_head", () -> new MegaloHeadItem());
	public static final RegistryObject<Item> MEGALO_BODY = REGISTRY.register("megalo_body", () -> new MegaloBodyItem());
	public static final RegistryObject<Item> MEGALO_ARMS = REGISTRY.register("megalo_arms", () -> new MegaloArmsItem());
	public static final RegistryObject<Item> MEGALO_LEGS = REGISTRY.register("megalo_legs", () -> new MegaloLegsItem());
	public static final RegistryObject<Item> MEGALO_HEAD_BLANK = REGISTRY.register("megalo_head_blank", () -> new MegaloHeadBlankItem());
	public static final RegistryObject<Item> MEGALO_BODY_BLANK = REGISTRY.register("megalo_body_blank", () -> new MegaloBodyBlankItem());
	public static final RegistryObject<Item> MEGALO_ARMS_BLANK = REGISTRY.register("megalo_arms_blank", () -> new MegaloArmsBlankItem());
	public static final RegistryObject<Item> MEGALO_LEGS_BLANK = REGISTRY.register("megalo_legs_blank", () -> new MegaloLegsBlankItem());
	public static final RegistryObject<Item> VENATOR_HEAD = REGISTRY.register("venator_head", () -> new VenatorHeadItem());
	public static final RegistryObject<Item> VENTATOR_BODY = REGISTRY.register("ventator_body", () -> new VentatorBodyItem());
	public static final RegistryObject<Item> VENATOR_ARMS = REGISTRY.register("venator_arms", () -> new VenatorArmsItem());
	public static final RegistryObject<Item> VENATOR_LEGS = REGISTRY.register("venator_legs", () -> new VenatorLegsItem());
	public static final RegistryObject<Item> VENATOR_HEAD_BLANK = REGISTRY.register("venator_head_blank", () -> new VenatorHeadBlankItem());
	public static final RegistryObject<Item> VENATOR_BODY_BLANK = REGISTRY.register("venator_body_blank", () -> new VenatorBodyBlankItem());
	public static final RegistryObject<Item> VENATOR_ARMS_BLANK = REGISTRY.register("venator_arms_blank", () -> new VenatorArmsBlankItem());
	public static final RegistryObject<Item> VENATOR_LEGS_BLANK = REGISTRY.register("venator_legs_blank", () -> new VenatorLegsBlankItem());
	public static final RegistryObject<Item> S_RAPTOR_HEAD = REGISTRY.register("s_raptor_head", () -> new SRaptorHeadItem());
	public static final RegistryObject<Item> S_RAPTOR_BODY = REGISTRY.register("s_raptor_body", () -> new SRaptorBodyItem());
	public static final RegistryObject<Item> S_RAPTOR_ARMS = REGISTRY.register("s_raptor_arms", () -> new SRaptorArmsItem());
	public static final RegistryObject<Item> S_RAPTOR_LEGS = REGISTRY.register("s_raptor_legs", () -> new SRaptorLegsItem());
	public static final RegistryObject<Item> S_RAPTOR_HEAD_BLANK = REGISTRY.register("s_raptor_head_blank", () -> new SRaptorHeadBlankItem());
	public static final RegistryObject<Item> S_RAPTOR_BODY_BLANK = REGISTRY.register("s_raptor_body_blank", () -> new SRaptorBodyBlankItem());
	public static final RegistryObject<Item> S_RAPTOR_ARMS_BLANK = REGISTRY.register("s_raptor_arms_blank", () -> new SRaptorArmsBlankItem());
	public static final RegistryObject<Item> S_RAPTOR_LEGS_BLANK = REGISTRY.register("s_raptor_legs_blank", () -> new SRaptorLegsBlankItem());
	public static final RegistryObject<Item> GIGANTO_HEAD = REGISTRY.register("giganto_head", () -> new GigantoHeadItem());
	public static final RegistryObject<Item> GIGANTO_BODY = REGISTRY.register("giganto_body", () -> new GigantoBodyItem());
	public static final RegistryObject<Item> GIGANTO_ARMS = REGISTRY.register("giganto_arms", () -> new GigantoArmsItem());
	public static final RegistryObject<Item> GIGANTO_LEGS = REGISTRY.register("giganto_legs", () -> new GigantoLegsItem());
	public static final RegistryObject<Item> GIGANTO_HEAD_BLANK = REGISTRY.register("giganto_head_blank", () -> new GigantoHeadBlankItem());
	public static final RegistryObject<Item> GIGANTO_BODY_BLANK = REGISTRY.register("giganto_body_blank", () -> new GigantoBodyBlankItem());
	public static final RegistryObject<Item> GIGANTO_ARMS_BLANK = REGISTRY.register("giganto_arms_blank", () -> new GigantoArmsBlankItem());
	public static final RegistryObject<Item> GIGANTO_LEGS_BLANK = REGISTRY.register("giganto_legs_blank", () -> new GigantoLegsBlankItem());
	public static final RegistryObject<Item> CRYO_HEAD = REGISTRY.register("cryo_head", () -> new CryoHeadItem());
	public static final RegistryObject<Item> CRYO_BODY = REGISTRY.register("cryo_body", () -> new CryoBodyItem());
	public static final RegistryObject<Item> CRYO_ARMS = REGISTRY.register("cryo_arms", () -> new CryoArmsItem());
	public static final RegistryObject<Item> CRYO_LEGS = REGISTRY.register("cryo_legs", () -> new CryoLegsItem());
	public static final RegistryObject<Item> CRYO_HEAD_BLANK = REGISTRY.register("cryo_head_blank", () -> new CryoHeadBlankItem());
	public static final RegistryObject<Item> CRYO_BODY_BLANK = REGISTRY.register("cryo_body_blank", () -> new CryoBodyBlankItem());
	public static final RegistryObject<Item> CRYO_ARMS_BLANK = REGISTRY.register("cryo_arms_blank", () -> new CryoArmsBlankItem());
	public static final RegistryObject<Item> CRYO_LEGS_BLANK = REGISTRY.register("cryo_legs_blank", () -> new CryoLegsBlankItem());
	public static final RegistryObject<Item> CARCHAR_HEAD = REGISTRY.register("carchar_head", () -> new CarcharHeadItem());
	public static final RegistryObject<Item> CARCHAR_BODY = REGISTRY.register("carchar_body", () -> new CarcharBodyItem());
	public static final RegistryObject<Item> CARCHAR_ARMS = REGISTRY.register("carchar_arms", () -> new CarcharArmsItem());
	public static final RegistryObject<Item> CARCHAR_LEGS = REGISTRY.register("carchar_legs", () -> new CarcharLegsItem());
	public static final RegistryObject<Item> CARCHAR_HEAD_BLANK = REGISTRY.register("carchar_head_blank", () -> new CarcharHeadBlankItem());
	public static final RegistryObject<Item> CARCHAR_BODY_BLANK = REGISTRY.register("carchar_body_blank", () -> new CarcharBodyBlankItem());
	public static final RegistryObject<Item> CARCHAR_ARMS_BLANK = REGISTRY.register("carchar_arms_blank", () -> new CarcharArmsBlankItem());
	public static final RegistryObject<Item> CARCHAR_LEGS_BLANK = REGISTRY.register("carchar_legs_blank", () -> new CarcharLegsBlankItem());
	public static final RegistryObject<Item> ACRO_HEAD = REGISTRY.register("acro_head", () -> new AcroHeadItem());
	public static final RegistryObject<Item> ACRO_BODY = REGISTRY.register("acro_body", () -> new AcroBodyItem());
	public static final RegistryObject<Item> ACRO_ARMS = REGISTRY.register("acro_arms", () -> new AcroArmsItem());
	public static final RegistryObject<Item> ACRO_LEGS = REGISTRY.register("acro_legs", () -> new AcroLegsItem());
	public static final RegistryObject<Item> ACRO_HEAD_BLANK = REGISTRY.register("acro_head_blank", () -> new AcroHeadBlankItem());
	public static final RegistryObject<Item> ACRO_BODY_BLANK = REGISTRY.register("acro_body_blank", () -> new AcroBodyBlankItem());
	public static final RegistryObject<Item> ACRO_ARMS_BLANK = REGISTRY.register("acro_arms_blank", () -> new AcroArmsBlankItem());
	public static final RegistryObject<Item> ACRO_LEGS_BLANK = REGISTRY.register("acro_legs_blank", () -> new AcroLegsBlankItem());
	public static final RegistryObject<Item> F_RAPTOR_HEAD = REGISTRY.register("f_raptor_head", () -> new FRaptorHeadItem());
	public static final RegistryObject<Item> F_RAPTOR_BODY = REGISTRY.register("f_raptor_body", () -> new FRaptorBodyItem());
	public static final RegistryObject<Item> F_RAPTOR_ARMS = REGISTRY.register("f_raptor_arms", () -> new FRaptorArmsItem());
	public static final RegistryObject<Item> F_RAPTOR_LEGS = REGISTRY.register("f_raptor_legs", () -> new FRaptorLegsItem());
	public static final RegistryObject<Item> F_RAPTOR_HEAD_BLANK = REGISTRY.register("f_raptor_head_blank", () -> new FRaptorHeadBlankItem());
	public static final RegistryObject<Item> F_RAPTOR_BODY_BLANK = REGISTRY.register("f_raptor_body_blank", () -> new FRaptorBodyBlankItem());
	public static final RegistryObject<Item> F_RAPTOR_ARMS_BLANK = REGISTRY.register("f_raptor_arms_blank", () -> new FRaptorArmsBlankItem());
	public static final RegistryObject<Item> F_RAPTOR_LEGS_BLANK = REGISTRY.register("f_raptor_legs_blank", () -> new FRaptorLegsBlankItem());
	public static final RegistryObject<Item> CARCHAR_SPAWN_EGG = REGISTRY.register("carchar_spawn_egg", () -> new ForgeSpawnEggItem(FossilMinecraftModEntities.CARCHAR, -3355648, -16764007, new Item.Properties()));
	public static final RegistryObject<Item> SPINAX_HEAD = REGISTRY.register("spinax_head", () -> new SpinaxHeadItem());
	public static final RegistryObject<Item> SPINAX_BODY = REGISTRY.register("spinax_body", () -> new SpinaxBodyItem());
	public static final RegistryObject<Item> SPINAX_ARMS = REGISTRY.register("spinax_arms", () -> new SpinaxArmsItem());
	public static final RegistryObject<Item> SPINAX_LEGS = REGISTRY.register("spinax_legs", () -> new SpinaxLegsItem());
	public static final RegistryObject<Item> SPINAX_HEAD_BLANK = REGISTRY.register("spinax_head_blank", () -> new SpinaxHeadBlankItem());
	public static final RegistryObject<Item> SPINAX_BODY_BLANK = REGISTRY.register("spinax_body_blank", () -> new SpinaxBodyBlankItem());
	public static final RegistryObject<Item> SPINAX_ARMS_BLANK = REGISTRY.register("spinax_arms_blank", () -> new SpinaxArmsBlankItem());
	public static final RegistryObject<Item> SPINAX_LEGS_BLANK = REGISTRY.register("spinax_legs_blank", () -> new SpinaxLegsBlankItem());
	public static final RegistryObject<Item> NEO_HEAD = REGISTRY.register("neo_head", () -> new NeoHeadItem());
	public static final RegistryObject<Item> NEO_BODY = REGISTRY.register("neo_body", () -> new NeoBodyItem());
	public static final RegistryObject<Item> NEO_ARMS = REGISTRY.register("neo_arms", () -> new NeoArmsItem());
	public static final RegistryObject<Item> NEO_LEGS = REGISTRY.register("neo_legs", () -> new NeoLegsItem());
	public static final RegistryObject<Item> NEO_HEAD_BLANK = REGISTRY.register("neo_head_blank", () -> new NeoHeadBlankItem());
	public static final RegistryObject<Item> NEO_BODY_BLANK = REGISTRY.register("neo_body_blank", () -> new NeoBodyBlankItem());
	public static final RegistryObject<Item> NEO_ARMS_BLANK = REGISTRY.register("neo_arms_blank", () -> new NeoArmsBlankItem());
	public static final RegistryObject<Item> NEO_LEGS_BLANK = REGISTRY.register("neo_legs_blank", () -> new NeoLegsBlankItem());
	public static final RegistryObject<Item> COMPSO_HEAD = REGISTRY.register("compso_head", () -> new CompsoHeadItem());
	public static final RegistryObject<Item> COMPSO_BODY = REGISTRY.register("compso_body", () -> new CompsoBodyItem());
	public static final RegistryObject<Item> COMPSO_ARMS = REGISTRY.register("compso_arms", () -> new CompsoArmsItem());
	public static final RegistryObject<Item> COMPSO_LEGS = REGISTRY.register("compso_legs", () -> new CompsoLegsItem());
	public static final RegistryObject<Item> COMPSO_HEAD_BLANK = REGISTRY.register("compso_head_blank", () -> new CompsoHeadBlankItem());
	public static final RegistryObject<Item> COMPSO_BODY_BLANK = REGISTRY.register("compso_body_blank", () -> new CompsoBodyBlankItem());
	public static final RegistryObject<Item> COMPSO_ARMS_BLANK = REGISTRY.register("compso_arms_blank", () -> new CompsoArmsBlankItem());
	public static final RegistryObject<Item> COMPSO_LEGS_BLANK = REGISTRY.register("compso_legs_blank", () -> new CompsoLegsBlankItem());
	public static final RegistryObject<Item> SOPTERYX_HEAD = REGISTRY.register("sopteryx_head", () -> new SopteryxHeadItem());
	public static final RegistryObject<Item> SOPTERYX_BODY = REGISTRY.register("sopteryx_body", () -> new SopteryxBodyItem());
	public static final RegistryObject<Item> SOPTERYX_ARMS = REGISTRY.register("sopteryx_arms", () -> new SopteryxArmsItem());
	public static final RegistryObject<Item> SOPTERYX_LEGS = REGISTRY.register("sopteryx_legs", () -> new SopteryxLegsItem());
	public static final RegistryObject<Item> SOPTERYX_HEAD_BLANK = REGISTRY.register("sopteryx_head_blank", () -> new SopteryxHeadBlankItem());
	public static final RegistryObject<Item> SOPTERYX_BODY_BLANK = REGISTRY.register("sopteryx_body_blank", () -> new SopteryxBodyBlankItem());
	public static final RegistryObject<Item> SOPTERYX_ARMS_BLANK = REGISTRY.register("sopteryx_arms_blank", () -> new SopteryxArmsBlankItem());
	public static final RegistryObject<Item> SOPTERYX_LEGS_BLANK = REGISTRY.register("sopteryx_legs_blank", () -> new SopteryxLegsBlankItem());
	public static final RegistryObject<Item> DELTA_HEAD = REGISTRY.register("delta_head", () -> new DeltaHeadItem());
	public static final RegistryObject<Item> DELTA_BODY = REGISTRY.register("delta_body", () -> new DeltaBodyItem());
	public static final RegistryObject<Item> DELTA_ARMS = REGISTRY.register("delta_arms", () -> new DeltaArmsItem());
	public static final RegistryObject<Item> DELTA_LEGS = REGISTRY.register("delta_legs", () -> new DeltaLegsItem());
	public static final RegistryObject<Item> DELTA_HEAD_BLANK = REGISTRY.register("delta_head_blank", () -> new DeltaHeadBlankItem());
	public static final RegistryObject<Item> DELTA_BODY_BLANK = REGISTRY.register("delta_body_blank", () -> new DeltaBodyBlankItem());
	public static final RegistryObject<Item> DELTA_ARMS_BLANK = REGISTRY.register("delta_arms_blank", () -> new DeltaArmsBlankItem());
	public static final RegistryObject<Item> DELTA_LEGS_BLANK = REGISTRY.register("delta_legs_blank", () -> new DeltaLegsBlankItem());
	public static final RegistryObject<Item> TRO_HEAD = REGISTRY.register("tro_head", () -> new TroHeadItem());
	public static final RegistryObject<Item> TRO_BODY = REGISTRY.register("tro_body", () -> new TroBodyItem());
	public static final RegistryObject<Item> TRO_ARMS = REGISTRY.register("tro_arms", () -> new TroArmsItem());
	public static final RegistryObject<Item> TRO_LEGS = REGISTRY.register("tro_legs", () -> new TroLegsItem());
	public static final RegistryObject<Item> NYCHUS_HEAD = REGISTRY.register("nychus_head", () -> new NychusHeadItem());
	public static final RegistryObject<Item> NYCHUS_BODY = REGISTRY.register("nychus_body", () -> new NychusBodyItem());
	public static final RegistryObject<Item> NYCHUS_ARMS = REGISTRY.register("nychus_arms", () -> new NychusArmsItem());
	public static final RegistryObject<Item> NYCHUS_LEGS = REGISTRY.register("nychus_legs", () -> new NychusLegsItem());
	public static final RegistryObject<Item> NYCHUS_HEAD_BLANK = REGISTRY.register("nychus_head_blank", () -> new NychusHeadBlankItem());
	public static final RegistryObject<Item> NYCHUS_BODY_BLANK = REGISTRY.register("nychus_body_blank", () -> new NychusBodyBlankItem());
	public static final RegistryObject<Item> NYCHUS_ARMS_BLANK = REGISTRY.register("nychus_arms_blank", () -> new NychusArmsBlankItem());
	public static final RegistryObject<Item> NYCHUS_LEGS_BLANK = REGISTRY.register("nychus_legs_blank", () -> new NychusLegsBlankItem());
	public static final RegistryObject<Item> M_RAPTOR_HEAD = REGISTRY.register("m_raptor_head", () -> new MRaptorHeadItem());
	public static final RegistryObject<Item> M_RAPTOR_BODY = REGISTRY.register("m_raptor_body", () -> new MRaptorBodyItem());
	public static final RegistryObject<Item> M_RAPTOR_ARMS = REGISTRY.register("m_raptor_arms", () -> new MRaptorArmsItem());
	public static final RegistryObject<Item> M_RAPTOR_LEGS = REGISTRY.register("m_raptor_legs", () -> new MRaptorLegsItem());
	public static final RegistryObject<Item> M_RAPTOR_HEAD_BLANK = REGISTRY.register("m_raptor_head_blank", () -> new MRaptorHeadBlankItem());
	public static final RegistryObject<Item> M_RAPTOR_BODY_BLANK = REGISTRY.register("m_raptor_body_blank", () -> new MRaptorBodyBlankItem());
	public static final RegistryObject<Item> M_RAPTOR_ARMS_BLANK = REGISTRY.register("m_raptor_arms_blank", () -> new MRaptorArmsBlankItem());
	public static final RegistryObject<Item> M_RAPTOR_LEGS_BLANK = REGISTRY.register("m_raptor_legs_blank", () -> new MRaptorLegsBlankItem());

	private static RegistryObject<Item> block(RegistryObject<Block> block) {
		return REGISTRY.register(block.getId().getPath(), () -> new BlockItem(block.get(), new Item.Properties()));
	}
}
